#!/bin/sh
#

## setup dependencies

apk add --no-cache \
    acme.sh \
    build-base \
    cmake \
    gcc \
    musl-dev \
    npm \
    openssl-dev \
    rustup

rustup-init --default-toolchain stable --no-modify-path -y
rustup target add x86_64-unknown-linux-musl

## build acme webview

cd /opt/webview

npm install
npm run build

## build acme server

cd /opt/server

source $HOME/.cargo/env
cargo build --release --target x86_64-unknown-linux-musl
