#!/bin/sh
#

cd /opt

export PATH="$PATH:$HOME/.acme.sh"
export PATH="$PATH:$HOME/.cargo/bin"

# -------------------------------------------------------
# setup dependencies

if [ ! -x /usr/bin/curl ]; then
    apk add openssl curl socat
fi

if [ ! -x ~/.acme.sh/acme.sh ]; then
    curl https://get.acme.sh | sh -s email=acme@rehi.org
    acme.sh --register-account --server letsencrypt
    acme.sh --set-default-ca --server letsencrypt
fi

# -------------------------------------------------------
# run dev server

cargo run
